{% set name = "javabridge" %}
{% set version = "1.0.18" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "d6d27dad4331fd1f4cc4a82aedd168bbc3d57641def8f055e137ae3cad521737" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  #script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - {{ compiler('c') }}
    #- openjdk
  host:
    - python
    - pip
    - cython
    - numpy
    - openjdk
    #- setuptools
  run:
    - python
    - cython
    - numpy
    - openjdk
    #- setuptools
    
test:
  imports:
    - javabridge
    - javabridge.tests
  requires:
    - nose
    - openjdk

about:
  home: http://github.com/CellProfiler/python-javabridge/
  license: BSD
  license_family: BSD
  summary: Python wrapper for the Java Native Interface
  description: "The python-javabridge package makes it easy to start a Java virtual\nmachine (JVM) from Python and interact with it. Python code can\ninteract with the JVM using a low-level API or a more\
    \ convenient\nhigh-level API. Python-javabridge was developed for and is used by the\ncell image analysis software CellProfiler (cellprofiler.org)."
  doc_url: 'https://pythonhosted.org/javabridge/'
  dev_url: 'http://github.com/CellProfiler/python-javabridge/'

extra:
  recipe-maintainers:
    - drpatelh
